gateways:
  ducklake:
    connection:
      type: duckdb
      catalogs:
        ducklake_db: 'ducklake:lakehouse.ducklake'
      extensions:
        - ducklake
  
    state_connection:
      type: duckdb
      database: state.duckdb

default_gateway: ducklake

model_defaults:
  dialect: duckdb
  start: 2025-05-29
