gateways:
  ducklake:
    connection:
      type: duckdb
      catalogs:
        lakehouse:
          type: ducklake
          path: lakehouse/metadata.ducklake
          # data_path: lakehouse/data # Not yet supported by SQLMesh
      extensions:
        - ducklake
  
    state_connection:
      type: duckdb
      database: lakehouse/state.duckdb

default_gateway: ducklake

model_defaults:
  dialect: duckdb
  start: 2025-05-29
