gateways:
  ducklake:
    connection:
      type: duckdb
      catalogs:
        ducklake:
          type: ducklake
          path: postgres:host={{ env_var('PG__HOST') }} dbname={{ env_var('PG__DATABASE') }} user={{ env_var('PG__USER') }} password={{ env_var('PG__PASSWORD') }}
          data_path: r2://ducklake
          encrypted: true
      extensions:
        - ducklake
        - httpfs
      secrets:
        - type: r2
          account_id: {{ env_var('R2__ACCOUNT_ID') }}
          key_id: {{ env_var('R2__ACCESS_KEY_ID') }}
          secret: {{ env_var('R2__SECRET_ACCESS_KEY') }}
  
    state_connection:
      type: postgres
      host: {{ env_var('PG__HOST') }}
      port: {{ env_var('PG__PORT') }}
      database: {{ env_var('PG__DATABASE') }}
      user: {{ env_var('PG__USER') }}
      password: endpoint={{ env_var('PG__ENDPOINT_ID') }};{{ env_var('PG__PASSWORD') }} # Neon requires endpoint_id
      sslmode: require

default_gateway: ducklake

model_defaults:
  dialect: duckdb
  start: 2025-05-29
